name: Django Тестирование и развертывание

on:
  push:
    branches:
      - main

jobs:
  django-tests:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "0"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DATABASE_PORT }}

    steps:
      - name: Проверка изменений репозитория
        uses: actions/checkout@v3

      - name: Установка python и окружения
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Установка зависимостей
        run: |
          pip install --upgrade pip
          pip install -r Task_2/requirements.txt

      - name: Линтинг
        run:
          flake8 3.2-crud/stocks_products

      - name: Тестирование
        run: | 
          cd 3.2-crud/stocks_products
          python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.DB_ENGINE }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}

      - name: Развертывание
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: expect /home/tanny/DJANGO/deploy.exp
            
            
          
